apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
      - name: knote-container
        image: learnk8s/knote-js:1.0.0
#        command: [ "/bin/sh", "-c", "env" ]
        envFrom:
        - secretRef:
            name: secret-to-be-created
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: mongodb://mongo:27017/dev
