apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: aws-secret1
    creationPolicy: Owner
#  data:
#  - secretKey: secret-key-to-be-managed
#    remoteRef:
#      key: provider-key
#      version: provider-key-version
#      property: provider-key-property
  dataFrom:
  - extract:
      key: aws-secret1
