apiVersion: v1
kind: Service
metadata:
  name: knote-service
spec:
  type: NodePort
  selector:
    app: knote
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001  # Optional: specify a static nodePort
