apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    {{- range $key, $value := .Values.service.selector }}
    {{ $key }}: {{ $value }}
    {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: knote
          image: learnk8s/knote-js:1.0.0
#          command: ["/bin/sh", "-c", "sleep 10000 && env"]
          envFrom:
          - secretRef:
              name: app-pod-secret
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
